### ISSUE TITLE
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'paragraphStyle' 

### ISSUE THREAD

**Issue by iOSUser110** [richardtop/CalendarKit#104]
Type 'NSAttributedStringKey' (aka 'NSString') has no member 'paragraphStyle' 

getting this errror in TimeLineView.swift file with xcode 9

**Comment by richardtop** [comment]
This issue should have been fixed [in this commit](https://github.com/richardtop/CalendarKit/commit/5fd127742e815c810f2b8a275537f213e472c85d#diff-7e36d505b483ae0c17efabd9860ead56).

Please, try to update the dependencies in order to fix it by running this command:
`pod update` in project root directory.
