### ISSUE TITLE
Support EventKit

### ISSUE THREAD

**Issue by grosch** [richardtop/CalendarKit#124]
Feature request:  Please support EKEvent from EventKit.

**Comment by richardtop** [comment]
A good idea.
For now, you may create your own _EventDescriptor_ and map its properties from _EKEvent_, achieving the same result.

**Comment by richardtop** [comment]
Implemented in the CalendarApp. EventKit won't be supported in the CalendarKit directly, as CK's role is just to be a UI layer, it's up to the application to determine what data source to use (and how to format it).

Since it's possible to have multiple options of how to work with the EventKit, I provide just a reference implementation here:
https://github.com/richardtop/CalendarApp/blob/master/Calendar/EKWrapper.swift
