### ISSUE TITLE
 Memory usage is too high. How to fix it?

### ISSUE THREAD

**Issue by daveleenew** [richardtop/CalendarKit#147]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
 Memory usage is too high. How to fix it?

I run the demo project. The moeny usage over to 180M...

Is there a way to fix it??  thanks

**Comment by daveleenew** [comment]
Okay thanks for your answer.

as you say "A quick way to reduce the memory footprint is to flatten the view hierearchy"

how i do this ? show me the code??? thanks ..hahah

**Comment by richardtop** [comment]
_A quick way to reduce the memory footprint is to flatten the view hierearchy_ means that the less views you have in _CalendarKit_, the better the memory footprint.

Currently, there are 2 points to attack:
1. CalendarKit uses 3 full pages to display a single calendar (current page, left and right). This could be reduced to 2 pages at most, taking about 30% of memory. (Might consider UIPageViewController which implements this behavior)
2. Flattening _container_ views - i.e. used just for convenience, and not to display the data, i.e. `TimelineContainerView`.

Both of them require changing the structure of the library, therefore they're not the easiest tasks.
Still, the memory footprint now is good enough for the most of the use cases, so this issue is not a priority.

**Comment by daveleenew** [comment]
Oh.I see . I try to modify display three pages to one page.But they're not the easiest tasks. HaHa.

anyway.thank you

**Comment by richardtop** [comment]
@daveleenew  Is it really an issue? Does your app crashes due to high memory consumption or receives memory warnings?

**Comment by fatenumber25** [comment]
I try to modify display three pages to one page too, and my last solution is here.

override func eventsForDate(_ date: Date) -> [EventDescriptor] {
        if let selectedDate = dayView.state?.selectedDate, selectedDate != date {
            return []
        }

       ......
       return events;
}

override func dayView(dayView: DayView, didMoveTo date: Date) {
       self.reloadData()
}

**Comment by jdtzmn** [comment]
@richardtop I haven't seen anything so far as crashes or memory warnings, but I know that in my implementation, scrolling up and down throughout the day is less responsive than I'd like (try comparing the apple calendar to the CalendarKit demo).

**Comment by richardtop** [comment]
Should be fixed in the latest releases.
