### ISSUE TITLE
Add a day of the week picker date picker.

### ISSUE THREAD

**Issue by fury21** [richardtop/CalendarKit#233]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

### Issue Description
Hi! I propose to add a day of the week picker date picker.

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
Please, illustrate your proposal.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by fury21** [comment]
![jaazpw9ql4ec](https://user-images.githubusercontent.com/30409500/69330953-fd0d6d80-0c64-11ea-840a-88eca06acb39.png)

**Comment by richardtop** [comment]
The picker is used only in the demo project and it is not used in the library at all. Feel free to submit the pull request, but since the picker is not used in the library, this change is of little interest.
The demo project is meant to be used only for developers to try the library or to actually develop and test the library code against some generic calendar app example.
