### ISSUE TITLE
Incorrect Date and Delete or remove Scheduled Event

### ISSUE THREAD

**Issue by pks297** [richardtop/CalendarKit#249]
### New Issue Checklist
1. I have already assigned a timezone through code but when I click on the calender then getting different timezone date-time, is it another way to change the timezone, code added below?
```
  lazy var customCalendar: Calendar = {
    let customNSCalendar = NSCalendar(identifier: NSCalendar.Identifier.gregorian)!
    customNSCalendar.timeZone = TimeZone(abbreviation: "IST")!
    let calendar = customNSCalendar as Calendar
    return calendar
  }()
calendar = customCalendar
dayView = DayView(calendar: calendar)
```

2. I am trying to delete newly added events like swipe but it's not deleting, it there any other way to delete the event?

3. Please let me know if the particular slot has already booked then how to disable that hourly slot, user can not click on that particular booked slot.

Thanks!

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by pks297** [comment]
Hi Team
please let me know any update regarding this issue.

**Comment by richardtop** [comment]
Hi, for the issue 1:

> 1. I have already assigned a timezone through code but when I click on the calender then getting different timezone date-time, is it another way to change the timezone, code added below?
> ```
>   lazy var customCalendar: Calendar = {
>     let customNSCalendar = NSCalendar(identifier: NSCalendar.Identifier.gregorian)!
>     customNSCalendar.timeZone = TimeZone(abbreviation: "IST")!
>     let calendar = customNSCalendar as Calendar
>     return calendar
>   }()
> calendar = customCalendar
> dayView = DayView(calendar: calendar)
> ```
> 

Please, provide more details, e.g. what are you trying to achieve and better, a sample project that reproduces the issue.


For the questions 2 and 3:
Please, override the delegate callbacks of the CalendarKit. Inside the needed callbacks (e.g. when the timeline is pressed), check, if another event occupies that space and simply do not call an event creation method of the CalendarKit.

I recommend asking questions 2 and 3 on StackOverflow with the `CalendarKit` tag, since GitHub Issues are for bug reports and feature requests.
