### ISSUE TITLE
How to set the begin date (not the current day) and set the range of timeline (not all days)?

### ISSUE THREAD

**Issue by nn75** [richardtop/CalendarKit#253]
### New Issue Checklist

- [x] Use the latest version of CalendarKit
- [x] I've read the [Contribution Guidelines](https://github.com/richardtop/CalendarKit/blob/master/CONTRIBUTING.md)
- [x] I've searched for [existing GitHub issues](https://github.com/richardtop/CalendarKit/issues)

##### Code I'm using with CalendarKit

```Swift

[INSERT CODE HERE]

```

#### Result I am trying to achieve

[INSERT API OR UI MOCKUPS HERE]

**Comment by richardtop** [comment]
Hi, feel free to correct me if I'm wrong.
As I understood the question, you'd like to limit the user to be unable to view events before and after certain dates, so that the calendar displays only a specific range. For example, 12th December 2019 to 12th of January 2020.

Currently, there is no such functionality and issues #34 and #54 already request these features.

If you'd like to simply show a different date (other than Today) when the calendar opens, it's as easy as invoking a `move(to:)` method on `viewWillAppear` lifecycle event:


```Swift
  override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    let desiredDate = Date()
    dayView.state?.move(to: desiredDate)
  }
```
