### ISSUE TITLE
EventView

### ISSUE THREAD

**Issue by danlozano** [richardtop/CalendarKit#30]
Realized that whenever a user clicks on an EventView I get the actual EventView back in the delegate method, BUT I have no way of knowing which actual Event (my own custom Model) they clicked.

I realize I could do some complicated logic by checking the Dates and trying to figure out which Event they actually clicked.

I "fixed" it locally by adding a    var extraData: Any?   property to EventView, then casting it back to my own model in the delegate.

Was thinking of a more elegant way to fix this since I think this could be a common issue.

The other way could be subclassing EventView, adding extra properties & logic, then casting the EventView back to my own subclass afterwards in the delegate method.

But for some reason I could not accomplish that. Something to do with the required initializer to be able to subclass EventView.

Would love to discuss an elegant approach to this.

Thanks for the great framework!

**Comment by richardtop** [comment]
Using a property to store `userInfo` is actually a very elegant solution to the problem.

Sooner or later I am going to decouple `EventViews` from the `DataSource`. This will make the library more modular overall and will help in implementing view reuse to increase performance. 
After re-writing CalendarKit to request `EventModel`s instead of `EventView`s, this problem will be solved, as those models could be passed around.
Here is the scheme of this architecture:
![untitled diagram 1](https://cloud.githubusercontent.com/assets/8013017/23735435/98afd216-0496-11e7-83f1-752d54dc52dc.png)

But until it is implemented, it is a good idea to store a data model in `EventView`, so it would be possible to identify which `Event` triggered the delegate method.

**Comment by danlozano** [comment]
Wow! Thanks for the awesome explanation!

So, do you think we should add a data and/or userInfo property to EventView for now?

Or do you prefer making EventView subclassable so it's up to the framework's user to add any data/logic to the subclass?

Or should we just wait until EventViews are decoupled from the DataSource, and just work around these issues for now locally without modifying CalendarKit?

Sorry for the questions, just want to do what you think is best!

THANKS :)

**Comment by richardtop** [comment]
I think that "we should add a data and/or userInfo property to EventView for now",
as `EventView` still be subclassible if needed.

As there are no date for when the framework will be decoupled, I think, your solution in #29 is good as the transition.

**Comment by richardtop** [comment]
Fixed in#29
