### ISSUE TITLE
Open calendar on click header label "Wednesday, April 7, 2021"

### ISSUE THREAD

**Issue by kumarkundan75** [richardtop/CalendarKit#302]
Hi @richardtop !
I want to open calendar on click SwipeLabelView that help user to select date from calendar and move to selected date.

There is any solution to this?

**Comment by richardtop** [comment]
Hi, there is no solution for this out of the box.
I suggest you doing the following to implement your idea:

1. Fork CK
2. Create your own version of SwipeLabelView, add gesture recognizers to it to handle the interaction
3. Add other code needed to handle the result, e.g. in your subclass of the `DayViewController`.


To simplify updates, I suggest creating a different class, e.g. `MySwipeLabel` and modify as little files as possible, so that you could easier apply changes from the upstream.

**Comment by jakmalof** [comment]
@kumarkundan75 Were you able to figure out a solution to this? I am trying to do something similar by having the calendar start by displaying a specific date instead of whatever the current date is.
