### ISSUE TITLE
reloadData issue

### ISSUE THREAD

**Issue by mukulm24** [richardtop/CalendarKit#84]
I guess reloadData of DayViewController runs on the main thread causing UI to freeze. Can you please look into it. Why does the UI hang on reloadData.

**Comment by richardtop** [comment]
Hi @mukulm24, thanks for reporting this issue.
CalendarKit does some processing on the main thread. To reproduce this issue I'd like to hear a little bit more about your environment, including
- Device
- Approximate number of events per screen.

Also, I'd recommend you to check, how the date is fetched and pinpoint which part of the code is actually causing UI to freeze (for example, by using Time Profiler)
I see potentially 2 causes here:
- A slow piece of code in CalendarKit (A library flaw)
- Inefficient data retrieval of `DayViewDataSource` (A client code flaw)

First issue could be fixed by improving the library, while the second could be fixed by pre-fetching events asynchronously, so when the `DayViewDataSource` is being asked for the data, it provides it immediately from cache.
