### ISSUE TITLE
Feature Request: Add support for localised 12-hour timeline

### ISSUE THREAD

**Issue by jameswwwebster** [richardtop/CalendarKit#94]
The 12 hour time line currently forces xAM, xPM and noon. AM and PM indicators for each locale should be used instead. e.g. 8µ.µ. to represent 8pm in Greek.

Having a look at how this is currently implemented, I think it may be more pertienent to remove "noon" and simply replace it with 12:00 / 12pm. This is likely to be a problem both in providing the translation of "noon" in each language and restricting the length of the string so that it fits. 

This is a feature that I plan to implement myself and submit as a pull request, however it would be good if there could be some feedback about potential pitfalls or suggested implementation before any work is done.

**Comment by richardtop** [comment]
It's a good idea, I think, showing `12:00` independent of user's locale will solve the problem.
I think, the optimal tradeoff to handle this issue could be as follows:
1. Show `Noon` if locale is English.
2. Show `12:00` in other locale.
3. Always show local period indicator translation, e.g. `µ.µ` instead of `PM` in Greek.

Apple does exactly the same, the standard iOS calendar does not show translations of the `Noon`, only `12:00`:
![image](https://user-images.githubusercontent.com/8013017/30968444-0a2e755c-a468-11e7-9654-9027a013ce5a.png)
